### ISSUE TITLE
Not displaying the right values for temperature for met.no

### ISSUE THREAD

**Issue by FenvyWorks** [pkissling/clock-weather-card#15] opened 2022-10-17 16:45 UTC
Seems like it doesn't work with met.no forecast for some reason.

![Capture](https://user-images.githubusercontent.com/39421725/196235179-2fdddaa2-cac4-4f20-9356-1cd605e05e0c.PNG)

**Comment by FenvyWorks** [comment] 2022-10-17 16:47
The right values in atributes would be

temperature: 28
humidity: 56
pressure: 1016.8
wind_bearing: 57.9
wind_speed: 19.1
forecast:
  - condition: rainy
    precipitation: 2.7
    temperature: 27.8
    templow: 21.4
    datetime: '2022-10-18T15:00:00+00:00'
    wind_bearing: 66.5
    wind_speed: 21.2
  - condition: rainy
    precipitation: 1
    temperature: 27.8
    templow: 21.1
    datetime: '2022-10-19T15:00:00+00:00'
    wind_bearing: 54.2
    wind_speed: 26.3

**Comment by pkissling** [comment] 2022-10-18 12:00
so this is not an issue anymore?

**Comment by FenvyWorks** [comment] 2022-10-18 12:07
Oh it still is, at least for the version published and available on HACS. I apologize for not making things clear.

**Comment by pkissling** [comment] 2022-10-18 14:40
i just tested the met.no integration with the latest published clock-weather-card version (1.0.3).
for my side it looks fine. 
![image](https://user-images.githubusercontent.com/33731393/196461598-c1a159a5-3a3d-4db7-868f-9f2076f11c97.png)

my hunch is that the data delivered by met.no might differ depending on your location (lat/long).
```
temperature: 20.3
temperature_unit: °C
humidity: 61
pressure: 1025.8
pressure_unit: hPa
wind_bearing: 274.4
wind_speed: 14
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- condition: cloudy
  datetime: '2022-10-19T10:00:00+00:00'
  wind_bearing: 54.5
  temperature: 16.3
  templow: 10.2
  wind_speed: 11.9
  precipitation: 0
- condition: cloudy
  datetime: '2022-10-20T10:00:00+00:00'
  wind_bearing: 77
  temperature: 18
  templow: 7.7
  wind_speed: 11.9
  precipitation: 0
- condition: rainy
  datetime: '2022-10-21T10:00:00+00:00'
  wind_bearing: 136.9
  temperature: 17.3
  templow: 10.4
  wind_speed: 11.2
  precipitation: 6.3
- condition: partlycloudy
  datetime: '2022-10-22T10:00:00+00:00'
  wind_bearing: 269.3
  temperature: 16.7
  templow: 10.9
  wind_speed: 11.5
  precipitation: 1.5
- condition: cloudy
  datetime: '2022-10-23T10:00:00+00:00'
  wind_bearing: 100.1
  temperature: 20.3
  templow: 8
  wind_speed: 12.2
  precipitation: 0.1

attribution: Weather forecast from met.no, delivered by the Norwegian Meteorological Institute.
friendly_name: Forecast Home
```

could you provide your lat/long to hopefully make me able to reproduce the problem?

**Comment by FenvyWorks** [comment] 2022-10-18 17:43
Sure here it is roughly 
latitude: -20.388 longitude: -40.3209 

But it might be something else. I tested with open weather and it also got me a scrambled data.
![Capture](https://user-images.githubusercontent.com/39421725/196503158-615d0b5a-d048-4ab5-911a-7f8663c1def6.PNG)
 
I might be the one at fault here somehow. After the update to the language is also weirdly defaulting to this. So if everything is breaking i might be doing something stupid haha

My config on the card:
```
type: custom:clock-weather-card
entity: weather.openweathermap
locale: pt-BR
```

**Comment by pkissling** [comment] 2022-10-18 18:25
`pt-BR` showing Danish language was caused by a bug i already fixed in https://github.com/pkissling/clock-weather-card/pull/27. should work in the release `1.0.4` (in the next few days). 

The only thing i see in your screenshot not working properly is the `NaN` temperature above the clock. That i will look into.
Other than that, the card renders correctly. The bars only appearing blueish is due to the fact that you only have a temp range from -6 to -3 😅
here you can find the corresponding temperature colors: https://github.com/pkissling/clock-weather-card/blob/master/src/clock-weather-card.ts#L37

**Comment by FenvyWorks** [comment] 2022-10-18 19:19
Haha the thing is i live in brazil those temps should be on the 20s

**Comment by pkissling** [comment] 2022-10-20 15:09
hi @FenvyWorks, can you please use the attached `.zip` file and provide the browser logs?
please extract the `.zip`. it will contain the `.js` file.
[clock-weather-card.js.zip](https://github.com/pkissling/clock-weather-card/files/9831422/clock-weather-card.js.zip)

**Comment by FenvyWorks** [comment] 2022-10-20 16:04
Here it is. I hope it helps.
[console log.log](https://github.com/pkissling/clock-weather-card/files/9831860/console.log.log)

**Comment by FenvyWorks** [comment] 2022-10-20 16:10
Here i had to remove some lines that gave away my external url.
[console log.log](https://github.com/pkissling/clock-weather-card/files/9831969/console.log.log)

**Comment by FenvyWorks** [comment] 2022-10-20 16:12
interesting it seems the entity couldn't be found somehow

```
clock-weather-card.js?hacstag=522634019105:233 Uncaught (in promise) Error: A entidade requerida de clima não foi encontrada.
    at Bt.getWeather (clock-weather-card.js?hacstag=522634019105:233:1925)
    at Bt.renderToday (clock-weather-card.js?hacstag=522634019105:187:34)
    at Bt.render (clock-weather-card.js?hacstag=522634019105:180:20)
    at Bt.update (clock-weather-card.js?hacstag=522634019105:23:405)
    at Bt.performUpdate (clock-weather-card.js?hacstag=522634019105:11:5057)
    at Bt.scheduleUpdate (clock-weather-card.js?hacstag=522634019105:11:4704)
    at Bt._$EC (clock-weather-card.js?hacstag=522634019105:11:4612) 
```

**Comment by pkissling** [comment] 2022-10-20 16:23
hmm the error message is pretty strange. this exception means that the weather entity cannot be found.
can you provide your cards `yaml` configuration?

please double check that the entity id of attribute `entity`  also exists in your home assistant developer tools section.

my configuration is the following:
```yaml
- type: custom:clock-weather-card
  entity: weather.home
```

**Comment by FenvyWorks** [comment] 2022-10-20 16:28
Ok im absolutely stupid, i figured it out, home assistant handles the entity different in the new update i think. I just updated it and now its working. I apologize for this mess, and i appreciate your attention and care man. Awesome work, issue is solved, home assistant needs to be up to date for it to work.

**Comment by pkissling** [comment] 2022-10-20 17:29
hehe, happy to hear you resolved the issue. cheers!

**Closed by pkissling** 2022-10-20 17:29 UTC
Labels: bug, weather provider
