### ISSUE TITLE
Values for Wind Speed & Air Pressure

### ISSUE THREAD

**Issue by mrmireaux** [pkissling/clock-weather-card#459] opened 2024-09-23 08:17 UTC
It would be great if you could define or add your own wind speed and air pressure values from your own weather station to the card.

**Comment by andreas131187** [comment] 2024-09-27 20:51
Yeah that would be great. That's the only thing I am missing

**Comment by Dieghito72** [comment] 2024-10-02 09:50
+1 for this

**Comment by pkissling** [comment] 2024-10-27 18:35
closing as duplicate of #76

**Closed by pkissling** 2024-10-27 18:35 UTC
