### ISSUE TITLE
Forecast weather icons not showing on some devices

### ISSUE THREAD

**Issue by spudje** [pkissling/clock-weather-card#178] opened 2023-04-23 21:29 UTC
**Release with the issue:**
1.0.14

**Last working release (if known):**
I think none

**Browser and Operating System:**
Working in Brave (Chromium) on Windows and in Hass Android companion app on Pixel 5.
Not working in Hass Android companion app on (hacked) Lenovo Smart Clock 2

**Description of problem:**

Forecast weather icons not showing in Hass Android companion app on (hacked) Lenovo Smart Clock 2, while they show fine on other devices/browsers

Working:
![image](https://user-images.githubusercontent.com/53037698/233867000-cfaacc45-4a40-40fd-b78c-331e599eab1f.png)

Non-working
![image](https://user-images.githubusercontent.com/53037698/233867039-27399e79-24d6-4f11-a6b2-1fbdd1698d60.png)

**Comment by polygon242** [comment] 2023-04-24 21:28
i confirm this bug, same setup. My card layout is smaller (2 colums).
is it a resoloution problem or do the icons fail to render because of minimal webengine?

**Comment by pkissling** [comment] 2023-05-02 08:46
hi guys,
i honestly don't know how to reproduce / analyse the issue. i changed my browser resolution, but was not able to reproduce the issue.
![image](https://user-images.githubusercontent.com/33731393/235621131-af587189-850b-43f5-862c-faeb0fc710eb.png)

**Comment by raymercury** [comment] 2023-06-01 22:11
Having the same issue with missing forecast icons on Samsung Smart Fridge.
Here is the user agent:
```
Mozilla/5.0 (Linux; Tizen 6.0; SAMSUNG Family Hub 6.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/1.0 Chrome/76.0.3809.146 Mobile Safari/537.36
```
I don't think it has to do with resolution. The forecast icons work perfectly on newer devices, but not for this particular device.

**Comment by ge8020** [comment] 2023-06-11 19:51
Hi everybody.
i have the same problem on a Sony Tablet Z running Android 9 (LineageOS).
user agent:
Mozilla/5.0 (Linux; Android 9; Xperia Tablet Z Wi-Fi Build/PQ3A.190801.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.138 Safari/537.36

but it works with the same configuration (Fully Kiosk Browser) on a Lenovo tab 10 (Stock Android 10) and a Sony Tablet Z2 (Lineage OS, Android 11)

regards!

**Comment by polygon242** [comment] 2023-10-15 13:05
as of v 2.0.1 the rendering of the clock fails completely, just yaml text displayed.

**Comment by skydado** [comment] 2023-11-05 13:52
> Having the same issue with missing forecast icons on Samsung Smart Fridge. Here is the user agent:
> 
> ```
> Mozilla/5.0 (Linux; Tizen 6.0; SAMSUNG Family Hub 6.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/1.0 Chrome/76.0.3809.146 Mobile Safari/537.36
> ```
> 
> I don't think it has to do with resolution. The forecast icons work perfectly on newer devices, but not for this particular device.

Same here, lost forecast icons on Samsung Smart Fridge tablet. Ok on other devices/browsers. Currently running v2, but I would say they were present in v1. @pkissling please do something ... thanks!

**Comment by polygon242** [comment] 2023-11-10 18:33
I hacked / rooted my smartclock to install new webkit, solving the problem (clientsided).

**Comment by iamjoshk** [comment] 2023-11-13 18:44
I was having the issue on my Fire HD 10 (2017) where clock-weather-card was not displaying. I used Fire Toolbox to sideload an updated webview apk com.amazon.webview.chromium to version 110.0.5481.154 and it's back to working.

**Comment by pkissling** [comment] 2024-01-12 07:45
via #243 i downgraded lit from v3 to v2 in order to solve compatibility issues. if the issue still persists, is has to do with an outdated browser engine running on your device. i'm afraid, there is not much i can do about it - sorry.
closing issue...

**Closed by pkissling** 2024-01-12 07:45 UTC
Labels: bug, blocked
