### ISSUE TITLE
Problem on a iPad mini 2 in the Mobile App

### ISSUE THREAD

**Issue by andreasfromch** [pkissling/clock-weather-card#91] opened 2022-10-30 07:00 UTC
I really love the “Clock Weather Card” and it works for me on almost every device perfect 😊!
But on my **iPad mini 2** in the **Mobile App** it looks like on the attached screenshot. The whole weather part is missing. Is there a possibility to fix it on my side or is there an update form your side necessary?
![iPad-Mini 2](https://user-images.githubusercontent.com/30843010/198866484-eae44e7c-4dc4-4dbf-8fea-0b2913f85643.png)

**Comment by pkissling** [comment] 2022-10-30 08:18
hi @andreasfromch,
i don't have an iPad mini, hence cannot reproduce the issue.
can you provide some additional details? ios version, resolution, browser, browser version

**Comment by andreasfromch** [comment] 2022-10-30 09:25
Hi @pkissling,
thanks for having a look into this issue.
I see that this problem must be hard to solve without an iPad with exact the same setup.
But here is the information

- iOS version: 12.5.5
- Screen resolution: 2048 x 1536
- Browser and browser version: I’m using the “native” Home Assistant App
- Page zoom in the App: 100%

I’ve already tried to change the settings in the App but that didn’t help. If I use a browser (_Chrome: 92.04515.90_) on the iPad, it shows the page as in the App itself.
Just for information I have multiple other devices especially a new iPad 6 and here everything looks just great.
I’ve tried to make a screenshot during a refresh, there it seems that the forecast is on the wrong position. After the refresh the part with green bar disappears completely.

![iPad-Mini 2 V2](https://user-images.githubusercontent.com/30843010/198871442-8487b309-2c24-41f1-be01-dc0b7d6ee55f.png)

**Comment by pkissling** [comment] 2022-10-30 11:00
ah, iOS12 again. can you check #81 to see if applying some card-mod modifications fix the issue?

**Comment by andreasfromch** [comment] 2022-10-30 12:05
Thanks s lot for that hint that fixed the problem on my iPad as well 👍😅😃!

**Comment by pkissling** [comment] 2022-10-30 14:21
the following version contains the mentioned css changes.
can you please try this version? if this makes your card work on iOS 12 (without card-mod), then i will include this change in the next release

[clock-weather-card.js.zip](https://github.com/pkissling/clock-weather-card/files/9896044/clock-weather-card.js.zip)

**Comment by andreasfromch** [comment] 2022-10-30 16:16
Hi @pkissling, thanks for the hotfix 😃!
It seems that the card shows up correctly now but the "dot" is still missing.

![iPad-Mini 3](https://user-images.githubusercontent.com/30843010/198889401-5e8ab765-18f3-400b-908e-8afeac6051cd.png)

**Comment by pkissling** [comment] 2022-10-30 16:19
one last attempt :D 
[clock-weather-card.js.zip](https://github.com/pkissling/clock-weather-card/files/9896276/clock-weather-card.js.zip)

**Comment by andreasfromch** [comment] 2022-10-30 16:35
Sorry, still no "dot" 😥😉...

**Comment by pkissling** [comment] 2022-10-30 17:30
okay, now i'm out of ideas on how to fix the issue without being able to reproduce it, sorry.
wondering though, why the fix did not work. 
[here](https://github.com/pkissling/clock-weather-card/issues/81#issuecomment-1296295853) the same issue was fixed with the exact same code changes

**Closed** 2022-10-31 09:40 UTC
Labels: bug

**Comment by andreasfromch** [comment] 2022-10-31 18:47
Thanks for the great support anyway 👍😀.
I will solve it with the additional style 🧐.
