### ISSUE TITLE
The current temperature indicator is not displayed.

### ISSUE THREAD

**Issue by Murianwind** [pkissling/clock-weather-card#56] opened 2022-10-20 21:57 UTC
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

![화면 캡처 2022-10-21 065040](https://user-images.githubusercontent.com/6447460/197066349-5ba4d2a5-ecf4-49d8-8bf0-7ffdfe0e6e98.png)

If the current temperature is lower than today's minimum temperature, the indicator showing the current temperature is not displayed.

And are there any options I need to set to apply hourly weather? I applied hourly weather entity so hourly weather information is not displayed.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by pkissling** [comment] 2022-10-21 06:52
hi @Murianwind, thanks for reporting the issue.
which weather provider are you using?

**Comment by Microbeen** [comment] 2022-10-21 07:48
I have a similar problem. 
The current temperature indicator is not displayed. 
It worked correctly before the update. 
Weather provider - Gismeteo.

**Comment by Murianwind** [comment] 2022-10-21 11:21
This is the weather component I am using.

https://github.com/GuGu927/damda_weather/

**Comment by pkissling** [comment] 2022-10-22 05:45
thanks for reporting the issue. 

although this issue is rather caused by inconsistent data by the weather provider (current temp is above/below the min/max temps of the forecast attribute), i did some modifications to the cards logic in order to properly adjust the min/max forecast values.

changes will be part of the next release.

**Closed** 2022-10-22 06:08 UTC
Labels: bug
