### ISSUE TITLE
hu locale, can't remove name of day 

### ISSUE THREAD

**Issue by Vizion-HUN** [pkissling/clock-weather-card#156] opened 2023-02-24 21:54 UTC
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
1.0.10 , 1.0.11
**Last working release (if known):**

**Browser and Operating System:**
Chrome, Win 10, all updated

**Description of problem:**

Hi! My config:
type: custom:clock-weather-card
entity: weather.forecast_otthon
sun_entity: sun.sun
weather_icon_type: fill
animated_icon: true
forecast_days: 5
locale: hu
time_format: 24
date_pattern: Y. MMMM d., EEEE
hide_today_section: false
hide_forecast_section: false
hide_clock: false
hide_date: false

Date result:
P, 2023. február 24, péntek

Problem is, the "P," at the start...
It should not be there...

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by pkissling** [comment] 2023-02-25 06:32
Duplicate of #89

**Closed** 2023-02-25 06:32 UTC
Labels: bug
